from __future__ import annotations

from typing import Any

from core.utils import write_text


def _metric(value: Any) -> str:
    return f"{value:.4f}" if isinstance(value, (int, float)) else "N/A"


def generate_phase1_report(
    report_path,
    source_summary: dict[str, Any],
    metrics: dict[str, Any],
    quality: dict[str, Any],
    freshness: dict[str, Any],
) -> None:
    """Write a source-grounded Markdown report for the baseline run."""
    quality_state = quality.get("great_expectations", {}).get("success", False)
    report = f"""# Phase 1 Baseline Report

## Source

| Field | Value |
| --- | --- |
| Source | {source_summary.get("source", "N/A")} |
| Query | {source_summary.get("query", "N/A")} |
| Filter | {source_summary.get("filter", "N/A")} |
| Clean records | {source_summary.get("records", "N/A")} |
| Run at | {source_summary.get("run_at", "N/A")} |

## Baseline metrics

| Metric | Value |
| --- | ---: |
| Samples | {metrics.get("samples", "N/A")} |
| Retrieval hit rate | {_metric(metrics.get("retrieval_hit_rate"))} |
| Mean Token F1 | {_metric(metrics.get("mean_token_f1"))} |
| Judge accuracy | {_metric(metrics.get("judge_accuracy"))} |
| Mean judge score | {_metric(metrics.get("mean_judge_score"))} |

## Data quality and freshness

| Signal | Value |
| --- | --- |
| Great Expectations pass | {quality_state} |
| Quality gate pass | {quality.get("success", False)} |
| Total rows | {freshness.get("total_rows", "N/A")} |
| Stale rows | {freshness.get("stale_rows", "N/A")} |
| Stale ratio | {_metric(freshness.get("stale_ratio"))} |
| Freshness SLA pass | {freshness.get("is_fresh", False)} |
| Latest published | {freshness.get("latest_published", "N/A")} |
| Oldest published | {freshness.get("oldest_published", "N/A")} |

## Notes

- Ragas: `{metrics.get("ragas", {})}`
- This report is generated from pipeline artifacts; do not edit metric values manually.
"""
    write_text(report_path, report)


def generate_corruption_report(
    report_path,
    baseline_metrics: dict[str, Any],
    corrupted_metrics: dict[str, Any],
    repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any],
    repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any],
    repaired_freshness: dict[str, Any],
) -> None:
    """Write an evidence-based comparison of baseline, corruption, and repair."""
    metric_rows = []
    for name in ("retrieval_hit_rate", "mean_token_f1", "judge_accuracy", "mean_judge_score"):
        baseline = baseline_metrics.get(name)
        corrupted = corrupted_metrics.get(name)
        repaired = repaired_metrics.get(name)
        degradation = corrupted - baseline if isinstance(corrupted, (int, float)) and isinstance(baseline, (int, float)) else None
        recovery = repaired - corrupted if isinstance(repaired, (int, float)) and isinstance(corrupted, (int, float)) else None
        metric_rows.append(
            f"| {name} | {_metric(baseline)} | {_metric(corrupted)} | {_metric(repaired)} | {_metric(degradation)} | {_metric(recovery)} |"
        )

    report = f"""# Corruption and Repair Comparison Report

## Performance comparison

| Metric | Baseline | Corrupted | Repaired | Change from baseline | Recovery from corrupted |
| --- | ---: | ---: | ---: | ---: | ---: |
{chr(10).join(metric_rows)}

## Data quality and freshness

| Signal | Corrupted | Repaired |
| --- | --- | --- |
| Quality gate pass | {corrupted_quality.get("success", False)} | {repaired_quality.get("success", False)} |
| Great Expectations pass | {corrupted_quality.get("great_expectations", {}).get("success", False)} | {repaired_quality.get("great_expectations", {}).get("success", False)} |
| Freshness SLA pass | {corrupted_freshness.get("is_fresh", False)} | {repaired_freshness.get("is_fresh", False)} |
| Stale rows | {corrupted_freshness.get("stale_rows", "N/A")} | {repaired_freshness.get("stale_rows", "N/A")} |
| Stale ratio | {_metric(corrupted_freshness.get("stale_ratio"))} | {_metric(repaired_freshness.get("stale_ratio"))} |

## Interpretation

- **Silent failure:** compare corrupted metrics and quality signals with baseline using the fixed evaluation set.
- **Repair:** the repaired dataset is rebuilt from `data/raw/crossref_records.json`, not patched from corrupted rows.
- **Evidence:** all values above are generated by the pipeline artifacts and should not be edited manually.
"""
    write_text(report_path, report)
